apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-api-deployment
  namespace: #{DEPLOY_K8S_NAMESPACE_PROD}#
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: statistics-service-api
  template:
    metadata:
      labels:
        app: statistics-service-api
    spec:
      containers:
      - image: #{BOATHOUSE_CONTAINER_REGISTRY}#/#{BOATHOUSE_ORG_NAME}#/boat-house-backend/statistics_service_api:#{env.BRANCH_NAME}#-#{env.BUILD_ID}#
        name: statistics-service-api
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always