name: Build and Deploy dev product-service
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build product-service
        run: docker build -f src/product-service/api/Dockerfile -t docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:action-ci src/product-service/api 

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push product_service_api tag branch number
        run : docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER}
      
      - name: docker push product_service_api tag latest
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:action-ci

  deploy-dev:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: list env
         run: env && ls

       - name: replace project name
         run: sed -i "s|docker.pkg.github.com\/idcf-boat-house\/boat-house|docker.pkg.github.com\/${GITHUB_REPOSITORY%/*}\/boat-house|g" devops/kompose/test/product-service-*.yaml

       - name: replace docker images tags
         run: sed -i "s|:latest$|:action-ci|g" devops/kompose/test/product-service-*.yaml

       - name: grep images url
         run: grep -i "image:" devops/kompose/kompose/test/product-service-*.yaml
         #run: ls devops/kompose/test/product-service-*.yaml

       - uses: Azure/k8s-set-context@v1
         with:
           kubeconfig: ${{ secrets.KUBE_CONFIG }}

       - uses: Azure/k8s-create-secret@v1
         with:
           container-registry-url: docker.pkg.github.com
           container-registry-username: ${GITHUB_REPOSITORY%/*}
           container-registry-password: ${{ secrets.packages_token }}
           secret-name: demo-k8s-secret

       - uses: Azure/k8s-deploy@v1
         with:
           namespace: 'boathouse-test-github'
           manifests: |
              devops/kompose/test/product-service-api-deployment.yaml
              devops/kompose/test/product-service-api-svc.yaml
              devops/kompose/test/product-service-db-deployment.yaml
              devops/kompose/test/product-service-db-svc.yaml
           kubectl-version: 'latest'
